#ifndef DESKTOP_UPDATER_NATIVE_VERSION_H_
#define DESKTOP_UPDATER_NATIVE_VERSION_H_

#define DESKTOP_UPDATER_NATIVE_API_VERSION 2u
#define DESKTOP_UPDATER_NATIVE_VERSION_STRING "3.1.4"

#endif  // DESKTOP_UPDATER_NATIVE_VERSION_H_
