#ifndef DESKTOP_UPDATER_NATIVE_VERSION_H_
#define DESKTOP_UPDATER_NATIVE_VERSION_H_

#define DESKTOP_UPDATER_NATIVE_ABI_VERSION 2u
#define DESKTOP_UPDATER_NATIVE_ABI_VERSION_1 1u
#define DESKTOP_UPDATER_NATIVE_VERSION_STRING "3.1.4"

#endif  // DESKTOP_UPDATER_NATIVE_VERSION_H_
